name       : fira-ttf
version    : 4.202
release    : 1
source     :
    - https://github.com/mozilla/Fira/archive/4.202.tar.gz : d86269657387f144d77ba12011124f30f423f70672e1576dc16f918bb16ddfe4
license    : OFL-1.1
component  : desktop.font
summary    : Mozilla's new typeface, used in Firefox OS
description: |
    Mozilla's new typeface, used in Firefox OS
install    : |
    fontdir=$installdir/usr/share/fonts/truetype/fira/
    install -dm644 $fontdir
    cp -R $workdir/ttf/*.ttf $fontdir